// Console UI text labels (Chinese).
// Extracted from dashboard.tsx for maintainability.

export const uiText = {
  loadFailed: "加载claw实例失败",
  loadImagesFailed: "加载镜像列表失败",
  createInstanceFailed: "创建实例失败",
  actionSubmittedPrefix: "动作已提交：",
  instanceCreatedPrefix: "实例创建成功：",
  actionFailed: "提交动作失败",
  pageTitle: "fun-ai-claw claw实例管理台",
  menuCollapse: "收起菜单",
  menuExpand: "展开菜单",
  menuInstances: "实例列表",
  menuAgents: "Agents",
  menuSkills: "Skills",
  menuMcp: "MCP",
  menuOpenPlatform: "开放平台",
  backToInstances: "返回实例列表",
  listTitle: "claw实例列表",
  listSubtitle: "点击任意 claw 实例进入详情",
  instanceDetailTitle: "实例详情",
  totalInstances: "实例总数",
  runningInstances: "运行中",
  stoppedInstances: "已停止",
  errorInstances: "异常实例",
  loadingInstances: "实例加载中...",
  refresh: "刷新",
  create: "新增实例",
  image: "镜像",
  gatewayHostPort: "网关端口",
  gatewayUrl: "访问地址",
  gatewayUrlUnavailable: "未分配",
  instanceName: "实例名",
  status: "状态",
  desiredState: "期望状态",
  updatedAt: "更新时间",
  detailTitlePrefix: "实例详情：",
  selectInstance: "请选择实例",
  instanceId: "实例ID",
  hostId: "宿主机ID",
  currentStatus: "当前状态",
  createdAt: "创建时间",
  start: "启动",
  stop: "停止",
  restartInstance: "重启实例",
  rollback: "回滚",
  delete: "删除",
  actionProgressTitle: "实例动作执行中",
  actionProgressHint: "请保持当前窗口在前台，系统正在处理指令。",
  actionProgressCurrent: "当前动作",
  actionProgressWaiting: "动作完成后将自动关闭此窗口。",
  remoteConnect: "远程连接",
  remoteConnectTitle: "远程命令行连接",
  remoteConnectHint: "复制下方命令后，在你的终端执行即可进入实例。",
  remoteConnectUnavailable: "未配置远程连接命令模板",
  remoteConnectCommand: "连接命令",
  webTerminal: "Web终端",
  connectTerminal: "连接终端",
  disconnectTerminal: "断开终端",
  openVisualUi: "UI可视化操作",
  openVisualUiUnavailable: "当前实例暂无可访问地址",
  pairingCode: "固定配对码",
  pairingLink: "配对链接",
  fetchPairingCode: "配对信息",
  pairingCodeTitle: "实例固定配对",
  pairingCodeHint: "优先点击下方配对链接，系统会自动带上访问令牌完成登录。",
  pairingCodeUnavailable: "暂时无法获取配对码，请稍后刷新。",
  pairingCodeFetchFailed: "获取配对码失败",
  refreshPairingCode: "刷新配对信息",
  pairingCodeFetchedAt: "获取时间",
  pairingCodeSource: "手动配对请求",
  sendCommand: "发送",
  terminalInputPlaceholder: "输入命令，回车可发送",
  terminalNotRunning: "实例未运行，无法打开Web终端",
  terminalConnectFailed: "Web终端连接失败",
  terminalConnected: "Web终端已连接",
  terminalDisconnected: "Web终端已断开",
  terminalOutput: "终端输出",
  copyCommand: "复制命令",
  copyCommandSuccess: "连接命令已复制",
  copyCommandFailed: "复制失败，请手动复制",
  confirmActionTitle: "确认操作",
  confirmActionContentPrefix: "确认对实例执行操作：",
  confirmActionOk: "确认执行",
  deleteConfirmTitle: "删除实例",
  deleteConfirmContentPrefix: "删除后不可恢复，确认删除：",
  deleteSuccessPrefix: "实例已删除：",
  deleteFailed: "删除实例失败",
  instanceNotFound: "实例不存在，已刷新列表",
  instanceIdCopied: "实例ID已复制",
  cancel: "取消",
  noInstances: "当前没有可管理的claw实例。",
  noAgentsSection: "Agents 区域暂未开放，下一步再对接分页功能。",
  noSkillsSection: "Skills 区域暂未开放，下一步再对接分页功能。",
  selectInstanceFirst: "请先在左侧实例列表选择一个 claw 实例。",
  createModalTitle: "创建新实例",
  desiredStateRunning: "运行",
  desiredStateStopped: "停止",
  noPresetImage: "当前没有可选预置镜像，请先在API配置 app.images.presets",
  imagePresetUpgrading: "镜像升级中，暂不可用",
  imagePresetShellOnlyHint: "当前开放 zeroclaw-shell 和 zeroclaw-python，其他内置镜像仍在升级中。",
  requiredName: "请输入实例名",
  nameAlreadyExists: "实例名已存在，请更换",
  requiredImage: "请选择镜像",
  fixedHostTipPrefix: "当前宿主机ID已固定：",
  agentChatTitle: "实例聊天",
  loadAgentsFailed: "加载 Agent 列表失败",
  noAgents: "该实例暂无可用 Agent",
  refreshAgents: "刷新 Agent 列表",
  agentListHint: "点击 Agent 卡片查看详情",
  loadSkillsFailed: "加载 Skill 列表失败",
  noSkills: "该实例暂无可用 Skill",
  tabClaw: "claw详情",
  tabConfig: "Config",
  tabChannel: "Channel",
  tabAgent: "Agent",
  tabSkill: "Skill",
  tabTask: "Task",
  agentSkillPanelTitle: "Agent / Skill",
  refreshSkills: "刷新 Skill 列表",
  selectSkill: "选择 Skill",
  skillListHint: "点击 Skill 卡片查看详情",
  skillAllowed: "可调用",
  skillNotAllowed: "未授权",
  skillPath: "Skill 路径",
  skillPrompt: "Skill 提示词",
  noSkillPrompt: "请选择 Skill 查看提示词",
  skillScopeHint: "Skill 属于实例工作区共享能力，当前 Agent 能否调用由 allowed_tools 限制",
  agentAllowedTools: "allowed_tools",
  agentSystemPromptTitle: "Agent system_prompt",
  agentSystemPromptPath: "配置路径",
  agentSystemPromptPreview: "system_prompt 预览",
  agentSystemPromptPlaceholder: "当前未配置 system_prompt",
  agentSystemPromptHint: "这里的修改会回写到 config.toml 中对应的 agents.<agentId>.system_prompt，并在实例运行中同步到 runtime。",
  agentSystemPromptEdit: "编辑",
  agentSystemPromptSave: "保存",
  agentSystemPromptCancel: "取消",
  agentSystemPromptSaving: "正在保存 system_prompt",
  agentSystemPromptSaved: "system_prompt 已保存",
  agentSystemPromptSaveFailed: "保存 system_prompt 失败",
  agentSystemPromptClearHint: "留空后保存会清空该 Agent 的 system_prompt 配置。",
  agentSkillNotAllowed: "当前 Agent 的 allowed_tools 未包含该 Skill ID，可能无法直接调用",
  selectAgent: "选择 Agent",
  agentModel: "模型",
  agentProvider: "提供方",
  agenticMode: "Agentic",
  agentMessage: "消息",
  agentMessagePlaceholder: "输入你想发送给当前会话的消息；未连接时，发送首条消息会自动启动会话。",
  sendAgentMessage: "发送到会话",
  missingAgentOrMessage: "请先选择 Agent 并输入消息",
  agentChatLegacyDisabled: "旧 agent-task 模式已移除，等待 Agent Session 模式接入",
  agentChatLegacyHint: "当前仅保留 UI，后续将改为长会话 Agent Session 驱动",
  agentSessionConnect: "启动会话",
  agentSessionDisconnect: "结束会话",
  agentSessionOutput: "会话输出",
  agentSessionOutputPlaceholder: "连接 Agent Session 后，实例内 zeroclaw agent 的输出会实时显示在这里。",
  agentSessionConnectFailed: "Agent Session 连接失败",
  agentSessionConnected: "Agent Session 已连接",
  agentSessionDisconnected: "Agent Session 已断开",
  agentSessionReconnect: "重新连接会话",
  agentSessionConnectFirst: "请先启动会话，再进行填写、发送或交互操作",
  agentSessionReconnectFirst: "当前连接已断开，发送消息会自动重连；如果需要，也可以手动重连。",
  agentSessionNotRunning: "请先启动实例，再打开 Agent Session",
  agentSessionControlIdleHint: "发送首条消息时会自动建立会话连接。",
  agentSessionControlActiveHint: "当前连接已就绪，可以继续对话、确认交互步骤或补充上下文。",
  agentSessionControlReconnectHint: "长时间未操作时断开属于正常现象。继续发送消息时会自动重连，也可以手动重连。",
  agentSessionModeHint: '当前为长会话模式，用户的"确认第N步 / 重生成"必须在同一条连接内继续发送。多行输入会被合并为单条消息，避免被 REPL 拆成多个回合。',
  agentSessionMainAgentHint: "会话模式决定由 claw 自动路由，还是直接进入你指定的 Agent。一旦关闭连接，上下文会立即清空。",
  agentSessionRouteMode: "会话模式",
  agentSessionRouteModeAuto: "自动路由",
  agentSessionRouteModeDirect: "指定 Agent",
  agentSessionRouteModeAutoHint: "不传 agentId，由 claw 先进入主 Agent，再自主选择或 delegate 给合适的 Agent。",
  agentSessionRouteModeDirectHint: "传入 agentId，会话直接进入当前所选 Agent，适合已知目标 Agent 的快速路径。",
  agentSessionCurrentAgent: "当前 Agent",
  agentSessionCurrentAgentHint: "会话会直接进入当前所选 Agent。连接建立后如需切换，请先结束当前会话。",
  agentSessionSelectAgentRequired: "请先选择一个 Agent 再启动会话",
  agentSessionNoAgentsAvailable: "当前实例没有可用 Agent，无法启动直连 Agent 会话",
  agentSessionStarterTitle: "发起创作需求",
  agentSessionStarterHint: "先用表单告诉 Agent 你要生成什么，后续再像聊天一样继续确认或修改。",
  agentSessionScriptType: "剧本类型",
  agentSessionScriptContent: "故事内容",
  agentSessionTargetAudience: "目标受众",
  agentSessionEpisodeCount: "预期集数",
  agentSessionSendStarter: "发送创作需求",
  agentSessionNeedStarterFields: "请先填写完整的创作需求",
  agentSessionStarterContentPlaceholder: "例如：一个被陷害的女律师重生回庭审前夜，反杀幕后黑手并逆袭成律所合伙人。",
  agentSessionFollowUpPlaceholder: "继续输入你想发送给当前会话的消息",
  agentSessionConversationEmpty: "会话消息和 Agent 回复会显示在这里。",
  agentSessionReviseModeTitle: "当前正在修改",
  agentSessionReviseModeHint: "请直接输入你的修改要求，系统会自动补齐交互协议字段。",
  agentSessionReviseModeCancel: "取消修改",
  agentSessionCopyOutput: "复制产出",
  agentSessionCopyOutputSuccess: "产出内容已复制",
  agentSessionCopyOutputFailed: "复制产出失败，请手动复制",
  agentSessionInteractionConfirmed: "已提交确认",
  agentSessionInteractionRevised: "已提交修改",
  agentSessionInteractionSubmitted: "已提交交互",
  agentSessionQuickApprove: "确认当前步骤",
  agentSessionQuickRevise: "重生成当前步骤",
  agentSessionShowDebug: "显示调试日志",
  agentSessionHideDebug: "隐藏调试日志",
  agentSessionDebugTitle: "调试日志",
  agentSessionActiveSession: "当前会话",
  agentSessionPendingReply: "Agent 正在组织回复...",
  agentSessionConnectedHint: "已连接到当前实例会话",
  agentSessionDisconnectedHint: "连接已断开",
  agentSessionIdleHint: "未连接",
  agentSessionDisconnectAlertTitle: "会话连接已断开",
  agentSessionDisconnectAlertDescription: "长时间未操作时连接断开属于正常现象。重新连接后，你可以继续操作。",
  agentSessionDisconnectAlertRestartDescription: "长时间未操作时连接断开属于正常现象。当前上下文已结束，重新连接后请重新发送你的上一条消息。",
  agentSessionConnectInterruptedTitle: "会话连接未建立成功",
  agentSessionConnectInterruptedDescription: "这次连接没有成功建立，你可以直接重试。",
  agentSessionDisconnectedSystemMessage: "会话连接已断开。长时间未操作时出现断开属于正常现象，请重新连接后继续。",
  agentSessionComposerShortcutHint: "Enter 发送，Shift + Enter 换行",
  mainAgentGuidanceTitle: "主 Agent 提示词",
  mainAgentGuidanceExpand: "展开",
  mainAgentGuidanceCollapse: "收起",
  mainAgentGuidanceRefresh: "刷新提示词",
  mainAgentGuidanceEdit: "编辑",
  mainAgentGuidanceCancel: "取消",
  mainAgentGuidanceSave: "保存覆盖",
  mainAgentGuidanceDelete: "删除覆盖",
  mainAgentGuidanceLoadingFailed: "加载主 Agent 提示词失败",
  mainAgentGuidanceSaveFailed: "保存主 Agent 提示词失败",
  mainAgentGuidanceDeleteFailed: "删除主 Agent 提示词覆盖失败",
  mainAgentGuidanceSaved: "主 Agent 提示词已保存",
  mainAgentGuidanceDeleted: "主 Agent 提示词覆盖已删除",
  mainAgentGuidanceSource: "生效来源",
  mainAgentGuidanceWorkspacePath: "运行路径",
  mainAgentGuidanceGlobalPath: "全局默认路径",
  mainAgentGuidanceOverwriteOnStart: "启动时覆盖",
  mainAgentGuidanceOverrideEnabled: "实例覆盖启用",
  mainAgentGuidanceOverridePrompt: "实例覆盖内容",
  mainAgentGuidanceOverridePromptPlaceholder: "输入或粘贴该实例的主 Agent 提示词",
  mainAgentGuidanceEffectivePrompt: "当前生效内容预览",
  mainAgentGuidanceNoEffectivePrompt: "当前无生效主 Agent 提示词",
  mainAgentGuidancePromptRequired: "首次保存实例覆盖时，请先填写提示词内容",
  // Task tab
  noTasks: "暂无定时任务",
  createTask: "创建任务",
  deleteTask: "删除",
  confirmDeleteTask: "确定删除该定时任务？",
  taskCreated: "任务创建成功",
  taskDeleted: "任务已删除",
  loadTasksFailed: "任务列表请求失败",
  taskCreateFailed: "创建任务失败",
  taskDeleteFailed: "删除任务失败",
  taskNamePlaceholder: "任务名称（可选）",
  taskSchedulePlaceholder: "Cron 表达式，如 0 9 * * *",
  taskCommandPlaceholder: "Shell 命令",
  taskScheduleRequired: "请输入 Cron 表达式",
  taskCommandRequired: "请输入 Shell 命令",
  taskCreatedJobs: "已创建的定时任务",
  taskCreateNew: "创建定时任务",
} as const;

export type UiText = typeof uiText;
